"""Add ActivationKey table

Revision ID: a1b2c3d4e5f6
Revises: 1a31ce608336
Create Date: 2026-01-01 05:14:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activationkey',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('jti', sa.String(), nullable=False),
        sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('student_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('issued_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_revoked', sa.Boolean(), nullable=False),
        sa.Column('used_count', sa.Integer(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activationkey_jti'), 'activationkey', ['jti'], unique=True)
    op.create_index(op.f('ix_activationkey_student_id'), 'activationkey', ['student_id'], unique=False)
    op.create_index(op.f('ix_activationkey_student_email'), 'activationkey', ['student_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activationkey_student_email'), table_name='activationkey')
    op.drop_index(op.f('ix_activationkey_student_id'), table_name='activationkey')
    op.drop_index(op.f('ix_activationkey_jti'), table_name='activationkey')
    op.drop_table('activationkey')
    # ### end Alembic commands ###
